FROM adoptopenjdk/openjdk11-openj9:jre-11.0.3_7_openj9-0.14.0-alpine
ENV KEYCLOAK_REALM=real
EXPOSE 8080
COPY target/*-hollow-thorntail.jar /deployments/hollow.jar
COPY target/*.war /deployments/app.war
ENTRYPOINT ["java", "-jar","-Djava.net.preferIPv4Stack=true","-Djava.net.preferIPv4Addresses=true", "/deployments/hollow.jar", "/deployments/app.war"]